linters:
  enable-all: true
  disable:
    # Disable deprecated linters
    - structcheck
    - nosnakecase
    - maligned
    - golint
    - interfacer
    - varcheck
    - exhaustivestruct
    - scopelint
    - deadcode
    - ifshort
    # Disable formatting linters except the used one
    - gofumpt
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - depguard
        - varnamelen
        - exhaustruct
        - funlen
linters-settings:
  depguard:
    rules:
      pkg:
        files:
          - pkg/**/*.go
        deny:
          - pkg: github.com/itimky/faraway-test/test
            desc: for tests only
