# https://vektra.github.io/mockery/latest/configuration/

log-level: warn
all: true
dir: 'test/{{ replaceAll .InterfaceDirRelative "github.com/itimky/faraway-test" "" }}'
outpkg: mocks
packages:
  io:
    config:
      all: false
    interfaces:
      Reader: { }

  net:
    config:
      all: false
    interfaces:
      Conn: { }

  github.com/itimky/faraway-test/pkg/book: { }

  github.com/itimky/faraway-test/pkg/server: { }

  github.com/itimky/faraway-test/pkg/client: { }
