version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    deploy:
      replicas: 5
    restart: always
