FROM golang:1.22.2-alpine3.19 AS builder
WORKDIR /src
RUN go env -w GOMODCACHE=/root/.cache/go-build
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/root/.cache/go-build go mod download
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build go build -o /go/bin/server ./cmd/server

FROM alpine:3.19
EXPOSE 5678

WORKDIR /app
COPY --from=builder /go/bin/server /app
CMD ["/app/server"]
