// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mockbook is an autogenerated mock type for the book type
type Mockbook struct {
	mock.Mock
}

type Mockbook_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockbook) EXPECT() *Mockbook_Expecter {
	return &Mockbook_Expecter{mock: &_m.Mock}
}

// GetRandomQuote provides a mock function with given fields:
func (_m *Mockbook) GetRandomQuote() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRandomQuote")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockbook_GetRandomQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomQuote'
type Mockbook_GetRandomQuote_Call struct {
	*mock.Call
}

// GetRandomQuote is a helper method to define mock.On call
func (_e *Mockbook_Expecter) GetRandomQuote() *Mockbook_GetRandomQuote_Call {
	return &Mockbook_GetRandomQuote_Call{Call: _e.mock.On("GetRandomQuote")}
}

func (_c *Mockbook_GetRandomQuote_Call) Run(run func()) *Mockbook_GetRandomQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mockbook_GetRandomQuote_Call) Return(_a0 string, _a1 error) *Mockbook_GetRandomQuote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockbook_GetRandomQuote_Call) RunAndReturn(run func() (string, error)) *Mockbook_GetRandomQuote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockbook creates a new instance of Mockbook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbook(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockbook {
	mock := &Mockbook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
